name = "TetrapodsRegistry"
uuid = "3ad6eb35-e9b2-4fd0-9e4b-714a2a233928"
repo = "git@github.com:UCD4IDS/TetrapodsRegistry.git"
description = "registry for the TETRAPODS Institute of Data Science at UC Davis"

[packages]
08a3b3d4-a326-42ad-8bf2-aae8cae0b9e1 = { name = "MonogenicFilterFlux", path = "M/MonogenicFilterFlux" }
196eb918-4f6f-4958-a9e4-adbde22f279d = { name = "ScatteringPlots", path = "S/ScatteringPlots" }
3d7dfd45-6c90-4c9b-b697-194a05757159 = { name = "FourierFilterFlux", path = "F/FourierFilterFlux" }
98074b08-0653-44f2-b80d-d0e4e1942d2e = { name = "TestPrivate", path = "T/TestPrivate" }
bd728e11-17d4-5679-9a00-f24958f87a1c = { name = "Shearlab", path = "S/Shearlab" }
d9cc96d6-3a18-48ba-a621-865d77ea2931 = { name = "HodgeEigs", path = "H/HodgeEigs" }
eadaac29-8b6b-5395-80fd-9ce36bb46293 = { name = "ScatteringTransform", path = "S/ScatteringTransform" }
f51caf9e-47b1-4165-a6d0-be29c4c287ce = { name = "KymatioWrapper", path = "K/KymatioWrapper" }
